// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TgCancelQrLogin() {
  return window['go']['main']['app']['TgCancelQrLogin']();
}

export function TgDeleteSession() {
  return window['go']['main']['app']['TgDeleteSession']();
}

export function TgGetNameByPeerID(arg1) {
  return window['go']['main']['app']['TgGetNameByPeerID'](arg1);
}

export function TgGetNameByUsername(arg1) {
  return window['go']['main']['app']['TgGetNameByUsername'](arg1);
}

export function TgGetQrCode() {
  return window['go']['main']['app']['TgGetQrCode']();
}

export function TgGetUserInfo() {
  return window['go']['main']['app']['TgGetUserInfo']();
}

export function TgIsAuthorized() {
  return window['go']['main']['app']['TgIsAuthorized']();
}

export function TgLoginWithPassword(arg1) {
  return window['go']['main']['app']['TgLoginWithPassword'](arg1);
}
