// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {telegram} from '../models';

export function TgCancelQrLogin():Promise<void>;

export function TgDeleteSession():Promise<string>;

export function TgGetNameByPeerID(arg1:number):Promise<telegram.GetNameResponse>;

export function TgGetNameByUsername(arg1:string):Promise<telegram.GetNameResponse>;

export function TgGetQrCode():Promise<telegram.GetQrCodeResponse>;

export function TgGetUserInfo():Promise<telegram.ProfileResponse>;

export function TgIsAuthorized():Promise<boolean>;

export function TgLoginWithPassword(arg1:string):Promise<string>;
